language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.2
    - extra-android-support
    - extra-android-m2repository
    - android-19
  licenses:
    - '.+'
script:
  - ./gradlew clean assemble check
